jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
unclassified:
  location:
    url: http://localhost:8080/
jobs:
  - script: >
      pipelineJob('self-study') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/alpekin98/self-study.git')
                }
                branch('*/main')
              }
            }
            lightweight()
          }
        }
      }
