# Get Jenkins image
FROM jenkins/jenkins:lts

ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
# RUN dpkg -i google-chrome-stable_current_amd64.deb
# RUN rm google-chrome-stable_current_amd64.deb
ENV CHROME_BIN=/usr/bin/google-chrome-stable
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
